copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot1\Plot1.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot10\Plot10.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot11\Plot11.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot12\Plot12.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot13\Plot13.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot14\Plot14.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot15\Plot15.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot16\Plot16.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot17\Plot17.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot18\Plot18.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot19\Plot19.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot2\Plot2.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot20\Plot20.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot21\Plot21.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot22\Plot22.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot23\Plot23.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot24\Plot24.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot25\Plot25.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot26\Plot26.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot27\Plot27.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot28\Plot28.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot29\Plot29.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot3\Plot3.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot30\Plot30.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot31\Plot31.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot32\Plot32.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot33\Plot33.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot34\Plot34.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot35\Plot35.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot36\Plot36.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot37\Plot37.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot38\Plot38.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot39\Plot39.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot4\Plot4.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot40\Plot40.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot41\Pot41.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot42\Plot42.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot43\Plot43.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot44\Plot44.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot45\Plot45.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot46\Plot46.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot47\Plot47.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot48\Plot48.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot49\Plot49.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot5\Plot5.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot50\Plot50.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot51\Plot51.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot52\Plot52.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot53\Plot53.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot54\Plot54.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot55\Plot55.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot56\Plot56.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot57\Plot57.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot58\Plot58.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot59\Plot59.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot6\Plot6.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot60\Plot60.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot61\Plot61.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot62\Plot62.png PlotScriptImages
copy D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot63\Plot62.png PlotScriptImages
