ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot1\Plot1.png Plot1.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot10\Plot10.png Plot10.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot11\Plot11.png Plot11.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot12\Plot12.png Plot12.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot13\Plot13.png Plot13.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot14\Plot14.png Plot14.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot15\Plot15.png Plot15.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot16\Plot16.png Plot16.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot17\Plot17.png Plot17.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot18\Plot18.png Plot18.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot19\Plot19.png Plot19.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot2\Plot2.png Plot2.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot20\Plot20.png Plot20.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot21\Plot21.png Plot21.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot22\Plot22.png Plot22.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot23\Plot23.png Plot23.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot24\Plot24.png Plot24.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot25\Plot25.png Plot25.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot26\Plot26.png Plot26.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot27\Plot27.png Plot27.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot28\Plot28.png Plot28.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot29\Plot29.png Plot29.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot3\Plot3.png Plot3.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot30\Plot30.png Plot30.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot31\Plot31.png Plot31.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot32\Plot32.png Plot32.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot33\Plot33.png Plot33.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot34\Plot34.png Plot34.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot35\Plot35.png Plot35.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot36\Plot36.png Plot36.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot37\Plot37.png Plot37.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot38\Plot38.png Plot38.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot39\Plot39.png Plot39.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot4\Plot4.png Plot4.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot40\Plot40.png Plot40.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot41\Pot41.png Pot41.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot42\Plot42.png Plot42.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot43\Plot43.png Plot43.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot44\Plot44.png Plot44.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot45\Plot45.png Plot45.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot46\Plot46.png Plot46.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot47\Plot47.png Plot47.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot48\Plot48.png Plot48.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot49\Plot49.png Plot49.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot5\Plot5.png Plot5.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot50\Plot50.png Plot50.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot51\Plot51.png Plot51.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot52\Plot52.png Plot52.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot53\Plot53.png Plot53.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot54\Plot54.png Plot54.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot55\Plot55.png Plot55.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot56\Plot56.png Plot56.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot57\Plot57.png Plot57.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot58\Plot58.png Plot58.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot59\Plot59.png Plot59.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot6\Plot6.png Plot6.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot60\Plot60.png Plot60.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot61\Plot61.png Plot61.png.save
ren D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot62\Plot62.png Plot62.png.save
