vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot1\Plot1.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot10\Plot10.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot11\Plot11.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot12\Plot12.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot13\Plot13.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot14\Plot14.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot15\Plot15.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot16\Plot16.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot17\Plot17.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot18\Plot18.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot19\Plot19.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot2\Plot2.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot20\Plot20.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot21\Plot21.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot22\Plot22.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot23\Plot23.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot24\Plot24.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot25\Plot25.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot26\Plot26.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot27\Plot27.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot28\Plot28.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot29\Plot29.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot3\Plot3.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot30\Plot30.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot31\Plot31.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot32\Plot32.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot33\Plot33.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot34\Plot34.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot35\Plot35.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot36\Plot36.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot37\Plot37.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot38\Plot38.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot39\Plot39.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot4\Plot4.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot40\Plot40.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot41\Plot41.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot42\Plot42.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot43\Plot43.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot44\Plot44.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot45\Plot45.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot46\Plot46.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot47\Plot47.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot48\Plot48.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot49\Plot49.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot5\Plot5.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot50\Plot50.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot51\Plot51.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot52\Plot52.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot53\Plot53.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot54\Plot54.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot55\Plot55.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot56\Plot56.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot57\Plot57.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot58\Plot58.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot59\Plot59.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot6\Plot6.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot60\Plot60.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot61\Plot61.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot62\Plot62.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot63\Plot63.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot64\Plot64.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot65\Plot65.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot66\Plot66.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot67\Plot67.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot68\Plot68.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot69\Plot69.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot7\Plot7.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot70\Plot70.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot71\Plot71.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot72\Plot72.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot73\Plot73.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot74\Plot74.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot8\Plot8.R
vim -s VimScript.txt D:\Code\R\LeastSquaresPlay\PlotsAndAssocCode\Plot9\Plot9.R
